### ISSUE TITLE
MOTD Blinding White on v4.2.0

### ISSUE THREAD

**Issue by xnaas** [SpaceLenore/thelounge-theme-dracula#2]
I'm not sure why, but MOTD messages are blinding white on v4.2.0-pre.2 of thelounge.

**Comment by xnaas** [comment]
For example, https://github.com/thelounge/thelounge-theme-solarized/commit/e5b741b65f8ccb21135ddc22078f355025b184db was added to Solarized to fix this issue, but Dracula already has that https://github.com/SpaceLenore/thelounge-theme-dracula/blob/master/dracula_theme.css#L281 and it doesn't seem to help? 🤔

**Comment by SpaceLenore** [comment]
Hi, thanks for reaching out. I currently run The Lounge v4.1.0 with thelounge-theme-dracula v1.1.0 and do not have that issue, however I had it after upgrading to The Lounge v4.1.0 and that was one of the reasons for the v1.1.0 patch. Could you please verify what theme version you're using?

**Comment by xnaas** [comment]
The issue is only present on `4.2.0-pre.2`. The issue was not present on `4.2.0-pre.1`. Nearly all themes appear to be affected.

Presumably my Dracula is as up-to-date as can be.

```
xnaas@xnaasSRV:~/docker$ docker exec --user node -it thelounge thelounge upgrade
2020-08-06 20:23:52 [INFO] Upgrading all packages...
2020-08-06 20:23:52 [INFO] Package(s) have been successfully upgraded.
xnaas@xnaasSRV:~/docker$ docker exec --user node -it thelounge thelounge outdated
2020-08-06 20:23:59 [INFO] Checking for outdated packages
2020-08-06 20:23:59 [INFO] No outdated packages
xnaas@xnaasSRV:~/docker$ docker exec --user node -it thelounge thelounge --version
v4.2.0-pre.2
```

**Comment by SpaceLenore** [comment]
I've looked into it a bit and adding the MOTD style to `#chat .msg[data-type="monospace_block"] .text` seems to fix the issue. 

However, this is a pre-release and things could change before the release candidate comes out so I'm hesitant about updating the theme in case it has unforeseen consequences in future releases, I think focus will be on being compatible with stable versions for now but I will take a moment to consider advantages / drawbacks of patching this now and perhaps see if there is a better css selector for it.

I've not been keeping up with the roadmap or development of The Lounge but if this is an unintentional change it might be worth getting in touch with them about it.

**Comment by xnaas** [comment]
The issue persists on the full release of 4.2.0.
